---
name: Test

on:
  push:
    branches: [main]
  pull_request:
    types: [opened, synchronize]
  workflow_dispatch:

jobs:
  tests:
    name: tests
    runs-on: ${{ matrix.os }}
    timeout-minutes: 10
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        rev: [nightly, v0.9.5, v0.10.2]
        include:
          - os: ubuntu-latest
            CONFIG_HOME: ~/.config/nvim
            PLUGINS_HOME: ~/.local/share/nvim/lazy
            LOGS_DIR: ~/.local/state
          - os: macos-latest
            CONFIG_HOME: ~/.config/nvim
            PLUGINS_HOME: ~/.local/share/nvim/lazy
            LOGS_DIR: ~/.local/state
          - os: windows-latest
            CONFIG_HOME: $env:LOCALAPPDATA\nvim
            PLUGINS_HOME: $env:LOCALAPPDATA\nvim-data\lazy
            LOGS_DIR: $env:LOCALAPPDATA\nvim-data
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - uses: rhysd/action-setup-vim@v1
        with:
          neovim: true
          version: ${{ matrix.rev }}
      - name: Prepare dependencies
        run: |
          nvim --version
          pip install cmake==3.21 ninja
          mkdir -p deps
          git clone --depth 1 https://github.com/nvim-lua/plenary.nvim.git deps/plenary.nvim
          git clone --depth 1 https://github.com/nvim-treesitter/nvim-treesitter.git deps/nvim-treesitter
          git clone --depth 1 https://github.com/nvim-neotest/neotest.git deps/neotest
          git clone --depth 1 https://github.com/nvim-neotest/nvim-nio.git deps/nvim-nio
          nvim --headless -u tests/unit/minimal_init.lua -c "TSInstallSync lua cpp" -c q
      - name: Run unit tests
        run: |
          nvim --headless -u tests/unit/minimal_init.lua -c "PlenaryBustedDirectory tests/unit {minimal_init='tests/unit/minimal_init.lua', sequential=true, timeout=5000}"
      # - name: Run integration tests
      #   run: |
      #     cd tests/integration/cmake && cmake -S . -B build && cmake --build build
      #     nvim --headless -u tests/unit/minimal_init.lua -c "PlenaryBustedDirectory tests/integration {minimal_init='tests/unit/minimal_init.lua', sequential=true, timeout=5000}"

